//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSettings
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public bool ShowApointmentInStart { get; set; }
        public bool ShowFollowInStart { get; set; }
        public bool ShowRestInStart { get; set; }
        public bool ShowDiscountInPaymentText { get; set; }
        public bool SaveSizes { get; set; }
        public bool WarningRestInApointment { get; set; }
        public bool AutoDefaultPaymentText { get; set; }
        public bool SaveGridLayout { get; set; }
        public bool ShowNextApointmentInExit { get; set; }
        public bool ShowNextFollowInExit { get; set; }
        public bool ShowNextRestInExit { get; set; }
        public bool ShowApointmentInInsert { get; set; }
        public bool InsertContractAfterOrder { get; set; }
        public Nullable<byte> PrintQty { get; set; }
        public bool GridPaging { get; set; }
        public Nullable<byte> PagingQty { get; set; }
        public bool ShowAllCustomer { get; set; }
        public bool LoadVisitorInCustomerDefine { get; set; }
        public string CashPaymentText { get; set; }
        public string MixPaymentText { get; set; }
        public string TimeInterval { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
