//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using ParsianOffice;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities() : base(ConnectionStringClass.GetConnectionString())
        {
        }
    
        public virtual DbSet<AppSettings> AppSettings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_ApKinds> tbl_ApKinds { get; set; }
        public virtual DbSet<tbl_Apointments> tbl_Apointments { get; set; }
        public virtual DbSet<tbl_ContactKind> tbl_ContactKind { get; set; }
        public virtual DbSet<tbl_Contract> tbl_Contract { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_CustomerPhone> tbl_CustomerPhone { get; set; }
        public virtual DbSet<tbl_ExpertKind> tbl_ExpertKind { get; set; }
        public virtual DbSet<tbl_ExpertPhone> tbl_ExpertPhone { get; set; }
        public virtual DbSet<tbl_Experts> tbl_Experts { get; set; }
        public virtual DbSet<tbl_FollowUP> tbl_FollowUP { get; set; }
        public virtual DbSet<tbl_Issues> tbl_Issues { get; set; }
        public virtual DbSet<tbl_OrderDetails> tbl_OrderDetails { get; set; }
        public virtual DbSet<tbl_OrderHeader> tbl_OrderHeader { get; set; }
        public virtual DbSet<tbl_OrderKind> tbl_OrderKind { get; set; }
        public virtual DbSet<tbl_PrintDesigns> tbl_PrintDesigns { get; set; }
        public virtual DbSet<tbl_PrintSettings> tbl_PrintSettings { get; set; }
        public virtual DbSet<tbl_Reason> tbl_Reason { get; set; }
        public virtual DbSet<tbl_Situation> tbl_Situation { get; set; }
        public virtual DbSet<tbl_UserAccess> tbl_UserAccess { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_Vacations> tbl_Vacations { get; set; }
        public virtual DbSet<viw_ApointmentReport> viw_ApointmentReport { get; set; }
        public virtual DbSet<viw_Contract> viw_Contract { get; set; }
        public virtual DbSet<viw_FollowUPs> viw_FollowUPs { get; set; }
    }
}
