//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FollowUP
    {
        public int ID { get; set; }
        public string fl_Text { get; set; }
        public Nullable<System.DateTime> fl_Date { get; set; }
        public Nullable<int> user_ID { get; set; }
        public string Date { get; set; }
        public Nullable<int> cu_ID { get; set; }
        public Nullable<int> changedUserID { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
    }
}
