//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExpertPhone
    {
        public int ID { get; set; }
        public Nullable<int> ep_ID { get; set; }
        public string ep_Field { get; set; }
        public string ep_Data { get; set; }
    
        public virtual tbl_Experts tbl_Experts { get; set; }
    }
}
