//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vacations
    {
        public int ID { get; set; }
        public string ep_Name { get; set; }
        public Nullable<System.DateTime> vc_StartDate { get; set; }
        public Nullable<System.DateTime> vc_EndDate { get; set; }
        public Nullable<int> ep_ID { get; set; }
        public string sh_StartDate { get; set; }
        public string sh_EndDate { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<int> ep_TimeRest { get; set; }
    
        public virtual tbl_Experts tbl_Experts { get; set; }
    }
}
