//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrintSettings
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool PreviewBeforePrint { get; set; }
        public bool LoadDesignBeforePrint { get; set; }
        public Nullable<byte> PrintQty { get; set; }
        public Nullable<int> DefaultDesignID { get; set; }
    
        public virtual tbl_PrintDesigns tbl_PrintDesigns { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
