//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetails
    {
        public int ID { get; set; }
        public Nullable<int> order_ID { get; set; }
        public Nullable<int> recID { get; set; }
        public Nullable<int> issue_ID { get; set; }
        public string issue_Name { get; set; }
        public Nullable<int> detail_Qty { get; set; }
        public Nullable<int> detail_Discount { get; set; }
        public Nullable<byte> detail_Discount_Per { get; set; }
        public Nullable<int> detail_Users { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> RecPrice { get; set; }
        public Nullable<int> detail_Price { get; set; }
        public Nullable<int> detail_RecPrice { get; set; }
        public string detail_Comment { get; set; }
        public bool detail_IsDone { get; set; }
    
        public virtual tbl_Issues tbl_Issues { get; set; }
        public virtual tbl_OrderHeader tbl_OrderHeader { get; set; }
    }
}
