//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_Apointments = new HashSet<tbl_Apointments>();
            this.tbl_CustomerPhone = new HashSet<tbl_CustomerPhone>();
            this.tbl_FollowUP = new HashSet<tbl_FollowUP>();
            this.tbl_OrderHeader = new HashSet<tbl_OrderHeader>();
        }
    
        public int cu_ID { get; set; }
        public string cu_Name { get; set; }
        public string cu_NationalCode { get; set; }
        public string cu_Email { get; set; }
        public string cu_Address { get; set; }
        public Nullable<int> vt_ID { get; set; }
        public string vt_Name { get; set; }
        public string cu_CustomName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Apointments> tbl_Apointments { get; set; }
        public virtual tbl_Experts tbl_Experts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerPhone> tbl_CustomerPhone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowUP> tbl_FollowUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderHeader> tbl_OrderHeader { get; set; }
    }
}
