//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OrderHeader()
        {
            this.tbl_Contract = new HashSet<tbl_Contract>();
            this.tbl_OrderDetails = new HashSet<tbl_OrderDetails>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> order_Date { get; set; }
        public Nullable<int> order_Side { get; set; }
        public string order_Comment { get; set; }
        public Nullable<int> order_BasePrice { get; set; }
        public Nullable<int> order_Dsicount { get; set; }
        public Nullable<int> order_Price { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<int> st_ID { get; set; }
        public string sh_Date { get; set; }
        public Nullable<int> order_kind { get; set; }
        public Nullable<int> changedUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Contract> tbl_Contract { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderDetails> tbl_OrderDetails { get; set; }
        public virtual tbl_OrderKind tbl_OrderKind { get; set; }
        public virtual tbl_Situation tbl_Situation { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
    }
}
