//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Apointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Apointments()
        {
            this.tbl_Reason = new HashSet<tbl_Reason>();
        }
    
        public int ID { get; set; }
        public Nullable<int> kind_ID { get; set; }
        public Nullable<System.DateTime> ap_Date { get; set; }
        public string ap_Area { get; set; }
        public Nullable<int> cu_ID { get; set; }
        public Nullable<int> expert_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<int> st_ID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Address { get; set; }
        public Nullable<int> changedUserID { get; set; }
        public string cu_Name { get; set; }
        public string cu_Phone { get; set; }
    
        public virtual tbl_ApKinds tbl_ApKinds { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Experts tbl_Experts { get; set; }
        public virtual tbl_Situation tbl_Situation { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_Users tbl_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Reason> tbl_Reason { get; set; }
    }
}
