//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAccess
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Section { get; set; }
        public Nullable<bool> InsertAccess { get; set; }
        public Nullable<bool> UpdateAccess { get; set; }
        public Nullable<bool> DeleteAccess { get; set; }
        public Nullable<bool> PrintAccess { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
