//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Experts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Experts()
        {
            this.tbl_Apointments = new HashSet<tbl_Apointments>();
            this.tbl_Customer = new HashSet<tbl_Customer>();
            this.tbl_ExpertPhone = new HashSet<tbl_ExpertPhone>();
            this.tbl_Vacations = new HashSet<tbl_Vacations>();
        }
    
        public int ID { get; set; }
        public string ep_Name { get; set; }
        public string ep_NationalCode { get; set; }
        public string ep_Address { get; set; }
        public Nullable<bool> ep_IsActive { get; set; }
        public Nullable<int> ep_kind { get; set; }
        public Nullable<byte> ep_DailyTimeWork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Apointments> tbl_Apointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Customer> tbl_Customer { get; set; }
        public virtual tbl_ExpertKind tbl_ExpertKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExpertPhone> tbl_ExpertPhone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Vacations> tbl_Vacations { get; set; }
    }
}
