//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.AppSettings = new HashSet<AppSettings>();
            this.tbl_Apointments = new HashSet<tbl_Apointments>();
            this.tbl_Apointments1 = new HashSet<tbl_Apointments>();
            this.tbl_Contract = new HashSet<tbl_Contract>();
            this.tbl_FollowUP = new HashSet<tbl_FollowUP>();
            this.tbl_FollowUP1 = new HashSet<tbl_FollowUP>();
            this.tbl_OrderHeader = new HashSet<tbl_OrderHeader>();
            this.tbl_OrderHeader1 = new HashSet<tbl_OrderHeader>();
            this.tbl_PrintSettings = new HashSet<tbl_PrintSettings>();
            this.tbl_UserAccess = new HashSet<tbl_UserAccess>();
        }
    
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> vt_ID { get; set; }
        public string kind { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSettings> AppSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Apointments> tbl_Apointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Apointments> tbl_Apointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Contract> tbl_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowUP> tbl_FollowUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowUP> tbl_FollowUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderHeader> tbl_OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderHeader> tbl_OrderHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrintSettings> tbl_PrintSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserAccess> tbl_UserAccess { get; set; }
    }
}
