//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_ApointmentReport
    {
        public string ep_Name { get; set; }
        public Nullable<System.DateTime> ap_Date { get; set; }
        public string ap_Area { get; set; }
        public int cu_ID { get; set; }
        public string cu_Name { get; set; }
        public string cu_NationalCode { get; set; }
        public string cu_Email { get; set; }
        public string cu_Address { get; set; }
        public string vt_Name { get; set; }
        public string st_Name { get; set; }
        public string kind_Name { get; set; }
        public string username { get; set; }
        public int ID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    }
}
