//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class viw_Contract
    {
        public int ID { get; set; }
        public string payment_Text { get; set; }
        public string sh_Date { get; set; }
        public Nullable<int> order_ID { get; set; }
        public Nullable<int> order_BasePrice { get; set; }
        public Nullable<int> order_Dsicount { get; set; }
        public Nullable<int> order_Price { get; set; }
        public string cu_Name { get; set; }
        public Nullable<int> vt_ID { get; set; }
        public string vt_Name { get; set; }
    }
}
